/*
 * servo.h
 *
 *  Created on: Apr 21, 2026
 *      Author: Mohamed
 */

#ifndef INC_SERVO_H_
#define INC_SERVO_H_

#ifdef __cplusplus
extern "C" {
#endif

/* ─────────────────────────── Includes ─────────────────────────── */
#include "stm32f1xx_hal.h"
#include <stdint.h>

/* ─────────────────────────── Default limits (µs) ──────────────── */
/** Standard hobby servo pulse range.
 *  Override per-instance via the Servo_Config fields if your servo differs. */
#define SERVO_DEFAULT_MIN_PULSE_US   500U   /**< Pulse width for   0° */
#define SERVO_DEFAULT_MAX_PULSE_US  2500U   /**< Pulse width for 180° */
#define SERVO_DEFAULT_MIN_ANGLE       0U    /**< Minimum angle (degrees) */
#define SERVO_DEFAULT_MAX_ANGLE     180U    /**< Maximum angle (degrees) */

/* ─────────────────────────── Status codes ─────────────────────── */
typedef enum
{
    SERVO_OK    = 0x00U,   /**< Operation successful          */
    SERVO_ERROR = 0x01U,   /**< General error                 */
    SERVO_BUSY  = 0x02U,   /**< Timer / channel busy          */
    SERVO_PARAM = 0x03U,   /**< Invalid parameter             */
} Servo_Status_t;

/* ─────────────────────────── Handle struct ────────────────────── */
/**
 * @brief  Servo instance handle.
 *
 * Fill in htim, channel, and (optionally) the pulse/angle limits before
 * calling Servo_Init().  All other fields are managed by the driver.
 */
typedef struct
{
    /* ── User-supplied (must set before Servo_Init) ── */
    TIM_HandleTypeDef *htim;        /**< Pointer to HAL timer handle
                                         (e.g. &htim2 generated by CubeMX) */
    uint32_t           channel;     /**< Timer channel macro
                                         TIM_CHANNEL_1 … TIM_CHANNEL_4     */

    uint16_t           min_pulse_us; /**< Pulse width for min angle (µs)   */
    uint16_t           max_pulse_us; /**< Pulse width for max angle (µs)   */
    uint8_t            min_angle;    /**< Minimum angle in degrees (0–180) */
    uint8_t            max_angle;    /**< Maximum angle in degrees (0–180) */

    /* ── Driver-managed (do not modify directly) ── */
    uint8_t            current_angle;   /**< Last commanded angle (°)      */
    uint16_t           current_pulse_us;/**< Last commanded pulse width (µs)*/
    uint8_t            is_initialized;  /**< 1 = init done, 0 = not ready  */
} Servo_Handle_t;

/* ─────────────────────────── API ──────────────────────────────── */

/**
 * @brief  Initialise a servo instance and start the PWM output.
 *
 * The underlying timer MUST already be initialised (by CubeMX-generated
 * MX_TIMx_Init) before calling this function.  This driver never calls
 * HAL_TIM_PWM_Init() or modifies the timer registers directly.
 *
 * If min_pulse_us / max_pulse_us / min_angle / max_angle are all zero the
 * driver fills them with the default values defined in this header.
 *
 * @param  hservo   Pointer to a user-allocated Servo_Handle_t.
 * @retval SERVO_OK on success, SERVO_PARAM / SERVO_ERROR otherwise.
 */
Servo_Status_t Servo_Init(Servo_Handle_t *hservo);

/**
 * @brief  Move the servo to a specific angle.
 *
 * @param  hservo   Pointer to an initialised Servo_Handle_t.
 * @param  angle    Target angle in degrees [min_angle … max_angle].
 * @retval SERVO_OK on success, SERVO_PARAM if angle is out of range.
 */
Servo_Status_t Servo_SetAngle(Servo_Handle_t *hservo, uint8_t angle);

/**
 * @brief  Set the servo position using a raw pulse width.
 *
 * Useful for fine-grained control or calibration beyond degree resolution.
 *
 * @param  hservo      Pointer to an initialised Servo_Handle_t.
 * @param  pulse_us    Pulse width in microseconds [min_pulse_us … max_pulse_us].
 * @retval SERVO_OK on success, SERVO_PARAM if pulse is out of range.
 */
Servo_Status_t Servo_SetPulse(Servo_Handle_t *hservo, uint16_t pulse_us);

/**
 * @brief  Read the last commanded angle.
 *
 * @param  hservo   Pointer to an initialised Servo_Handle_t.
 * @retval Current angle in degrees (0 if not initialised).
 */
uint8_t Servo_GetAngle(const Servo_Handle_t *hservo);

/**
 * @brief  Read the last commanded pulse width.
 *
 * @param  hservo   Pointer to an initialised Servo_Handle_t.
 * @retval Current pulse width in microseconds (0 if not initialised).
 */
uint16_t Servo_GetPulse(const Servo_Handle_t *hservo);

/**
 * @brief  Move the servo to its centre position (mid-angle).
 *
 * @param  hservo   Pointer to an initialised Servo_Handle_t.
 * @retval SERVO_OK on success.
 */
Servo_Status_t Servo_SetCenter(Servo_Handle_t *hservo);

/**
 * @brief  Stop the PWM output and de-energise the servo.
 *
 * After calling this function the servo handle is still valid; call
 * Servo_Init() again to restart it.
 *
 * @param  hservo   Pointer to an initialised Servo_Handle_t.
 * @retval SERVO_OK on success, SERVO_ERROR otherwise.
 */
Servo_Status_t Servo_Stop(Servo_Handle_t *hservo);

#ifdef __cplusplus
}
#endif

#endif /* INC_SERVO_H_ */
